import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout component is the root layout component for the Next.js application.
 * It renders the HTML structure with the specified children components.
 *
 * @param {Object} props - The component props.
 * @param {ReactNode} props.children - The children components.
 * @returns {JSX.Element} The rendered RootLayout component.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Render the HTML structure with the specified children components
  return (
    <html lang="en">
      {/* Set the class name of the body element to the class name of the Inter font */}
      <body className={inter.className}>
        {/* Render the specified children components */}
        {children}
      </body>
    </html>
  );
}
